<link href="/js/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/js/bootstrap/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="/js/bootstrap/css/bootstrap-theme.css">
<link rel="stylesheet" href="/js/jQuery-File-Upload-9.11.2/css/jquery.fileupload.css">
<link rel="stylesheet" href="/js/jQuery-File-Upload-9.11.2/css/jquery.fileupload-ui.css">
<script type="text/javascript" src="/js/jquery/jquery.js"></script>
<script type="text/javascript" src="/js/ajaxfileupload.js"></script>
<script type="text/javascript" src="/js/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/jQuery-File-Upload-9.11.2/js/vendor/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/js/jQuery-File-Upload-9.11.2/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="/js/jQuery-File-Upload-9.11.2/js/jquery.iframe-transport.js"></script>
